### ISSUE TITLE
请求

### ISSUE THREAD

**Issue by Goldenwang96** [Ki-Seki/MOPSO-for-Distribution#1]
您好：
        我是正在读研的学生，也在研究多目标的问题。您的这个代码写的非常好，所以想请问下可以看下关于代码的论文吗？
谢谢！

**Comment by Ki-Seki** [comment]
不好意思哈，论文是实验室的成果，而且论文还未发表，所以暂不能公开。不过你有什么问题的话可以私信我。我的微信号是：Ki-Seki。
