### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by Eco1i** [Ki-Seki/MOPSO-for-Distribution#2]
你好作者，在我运行该main方法的时候，出现了
      错误使用 matlab.graphics.chart.primitive.GraphPlot/set.NodeLabel
         'NodeLabel' 值必须为标量或长度为 50 的向量。
      出错 matlab.graphics.chart.primitive.GraphPlot
      
      出错 graph/plot (第 110 行)
      hObj = matlab.graphics.chart.primitive.GraphPlot('BasicGraph', ...
      
      出错 draw_net (第 53 行)
          plot(g, 'NodeLabel', 0:field.NODE_COUNT-1, 'EdgeLabel', g.Edges.Weight);
      出错 main (第 54 行)
      draw_net(field, graph_option);  % 绘制结点网络图
这个错误。在我是使用提供的数据集时，发生的，请问有什么解决办法么

**Comment by Ki-Seki** [comment]
已在 README.md 中添加解决方案，可以尝试下。

**Comment by Ki-Seki** [comment]
根本原因是不同MATLAB版本在计算包含换行的字符串时，使用了不同的统计规则，有的算换行符，有的不算换行符。
